#config-version=FGT60F-7.4.8-FW-build2795-250523:opmode=0:vdom=0:user=netadmin
#conf_file_ver=1027384955
#buildno=2795
#global_vdom=1
config system global
    set admin-lockout-duration 900
    set admin-lockout-threshold 3
    set admin-telnet disable
    set admintimeout 10
    set alias "FGT-EDGE"
    set hostname "FGT-EDGE"
    set pre-login-banner enable
    set timezone "Asia/Kolkata"
end
config system password-policy
    set status enable
    set minimum-length 15
end
config system interface
    edit "wan1"
        set vdom "root"
        set ip 198.51.100.2 255.255.255.252
        set allowaccess ping
        set type physical
        set role wan
        set alias "WAN uplink to ISP"
    next
    edit "internal"
        set vdom "root"
        set ip 10.20.0.1 255.255.255.0
        set allowaccess ping
        set type hard-switch
        set role lan
        set alias "LAN server segment"
    next
    edit "mgmt"
        set vdom "root"
        set ip 10.30.10.1 255.255.255.0
        set allowaccess ping https ssh
        set type physical
        set role lan
        set alias "OOB management"
    next
end
config system admin
    edit "netadmin"
        set accprofile "super_admin"
        set vdom "root"
        set trusthost1 10.30.10.0 255.255.255.0
        set ip6-trusthost1 fd00:30:10::/64
        set password ENC PB2PLACEHOLDERHASH
    next
    edit "tacacs-admins"
        set remote-auth enable
        set accprofile "super_admin"
        set vdom "root"
        set wildcard enable
        set remote-group "TACACS-ADMINS"
        set trusthost1 10.30.10.0 255.255.255.0
        set ip6-trusthost1 fd00:30:10::/64
    next
end
config user tacacs+
    edit "TACACS-1"
        set server "10.30.10.40"
        set key ENC PLACEHOLDERKEY
    next
end
config user group
    edit "TACACS-ADMINS"
        set member "TACACS-1"
    next
end
config log syslogd setting
    set status enable
    set server "10.30.10.50"
    set mode reliable
end
config system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "10.30.10.70"
            set authentication enable
            set key-type SHA256
            set key ENC PLACEHOLDERNTPKEY
            set key-id 1
        next
    end
end
config firewall address
    edit "all"
    next
    edit "LAN-NET"
        set subnet 10.20.0.0 255.255.255.0
    next
    edit "WEB-SRV"
        set subnet 10.20.0.10 255.255.255.255
    next
end
config firewall service custom
    edit "ALL"
        set category "General"
        set protocol IP
    next
    edit "DNS"
        set category "Network Services"
        set tcp-portrange 53
        set udp-portrange 53
    next
    edit "HTTPS"
        set category "Web Access"
        set tcp-portrange 443
    next
end
config firewall policy
    edit 1
        set name "LAN-to-internet"
        set srcintf "internal"
        set dstintf "wan1"
        set action accept
        set srcaddr "LAN-NET"
        set dstaddr "all"
        set schedule "always"
        set service "HTTPS" "DNS"
        set logtraffic all
        set nat enable
    next
    edit 2
        set name "deny-and-log"
        set srcintf "wan1"
        set dstintf "internal"
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end
